apiVersion: v1
kind: Service
metadata:
  name: akka-cluster-demo
  labels:
    app: akka-cluster-demo
spec:
  ports:
  - port: 8080
    name: http
  selector:
   app: akka-cluster-demo
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: akka-cluster-demo
spec:
  authentication: []
  hostname: akka-cluster-demo
  service:
    name: akka-cluster-demo
    port: 8080
